name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # استبدل <your-dockerhub-username> باسم المستخدم الخاص بك أو استخدم Secret
          tags: yaya0001 /lab6-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. الدخول لمجلد المشروع
            cd ~/lab8-cicd
            
            # 2. جلب آخر التعديلات (مثل docker-compose.yml و init.js)
            git pull origin main
            
            # 3. سحب الصورة الجديدة من Docker Hub
            docker compose pull
            
            # 4. إيقاف الحاويات القديمة وتنزيل الجديدة
            # ملاحظة: إذا أردت مسح البيانات القديمة لتفعيل init.js جديد، استخدم docker compose down -v
            docker compose down
            docker compose up -d
            
            # 5. تنظيف الصور القديمة غير المستخدمة لتوفير المساحة
            docker image prune -f
